version: 0.2

phases:
  install:
    commands:
      # Install dependencies
      - npm install

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  build:
    commands:
      - export REACT_APP_ENV=$APP_ENV
      - npm run build
      - aws s3 sync build/ s3://$S3_BUCKET --delete --acl public-read
      - aws cloudfront create-invalidation --distribution-id $CF_ID --paths '/*'
